name: Build Python Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.2'  # Use the version you are working with
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
          
      - name: Build executable
        run: |
          pyinstaller --onefile --console AlconsoleClient.py
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: AlconsoleClient-executable
          path: dist/
